# Generated by Django 2.0.2 on 2018-05-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField()),
                ('J_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='class_probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.TextField()),
                ('location', models.TextField()),
                ('vector', models.TextField()),
                ('map_num', models.TextField()),
                ('others', models.TextField()),
            ],
        ),
    ]
