# Generated by Django 2.0.2 on 2018-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android_respond', '0002_auto_20180212_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_android_user',
            name='user_TTL',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
