# Generated by Django 2.1.3 on 2019-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsc_data',
            name='BuildingID',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
