# Generated by Django 2.0.2 on 2018-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H5_introduce', '0002_auto_20180212_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_h5_introduce',
            name='J_img',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
